import Head from 'next/head'
import  Simple from '@/components/Sidebar'
import GridListWithHeading from '@/components/Features'
import ThreeTierPricingHorizontal from '@/components/Pricing'
import SmallWithNavigation from '@/components/Footer'
import WithBackgroundImage from '@/components/Hero'
import Contact from '@/components/Contact'
import WithSpeechBubbles from '@/components/Testimonials'
import Pricing from '@/components/Add'
import SplitWithImage1 from '@/components/ServicesAdd/index1'
import SplitWithImage2 from '@/components/ServicesAdd/index2'
import SplitWithImage3 from '@/components/ServicesAdd/index'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Simple/>
        <WithBackgroundImage/>
        <SplitWithImage1/>
        <SplitWithImage2/>
        <SplitWithImage3/>
        <WithSpeechBubbles/>
        <SmallWithNavigation/>
      </main>
    </>
  )
}
