import Head from 'next/head'
import * as React from 'react'
import SplitScreen from '@/components/body'
import Simple from '@/components/Bar/navbar'
import SmallWithNavigation from '@/components/Bar/footer'
import SplitWithImage from '@/components/body/service'
import SplitWithImage2 from '@/components/body/services2'
import SplitWithImage3 from '@/components/body/services3'



export default function Home() {
  return (
    <>
      <Head>
        <title>Alain Terrieur & co.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <SidebarWithHeader/> */}
        <Simple/>
        <SplitWithImage/>
        <SplitWithImage2/>
        <SplitWithImage3/>
        <SmallWithNavigation/>
      </main>
    </>
  )
}
